name: Create release note.

on:
  push:
    tags:
      - "*"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract tag name
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Extract release notes
        id: release_notes
        run: |
          RELEASE_NOTES=""
          CURRENT_LINE=0
          while IFS= read -r line; do
            if [[ "$line" == "## [$RELEASE_VERSION] - "* ]]; then
              CURRENT_LINE=1
            elif [[ "$CURRENT_LINE" == 1 && "$line" == "## ["* ]]; then
              CURRENT_LINE=0
            fi
            if [[ "$CURRENT_LINE" == 1 ]]; then
              RELEASE_NOTES="$RELEASE_NOTES"$'\n'"$line"
            fi
          done < "CHANGELOG.md"
          RELEASE_NOTES="${RELEASE_NOTES:2}" # 最後の改行を削除
          echo "::set-output name=body::$RELEASE_NOTES"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: v${{ env.RELEASE_VERSION }}
          body: ${{ steps.release_notes.outputs.body }}
